//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xamarinJKH {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xamarinJKH.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Л/сч: .
        /// </summary>
        internal static string Acc {
            get {
                return ResourceManager.GetString("Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключить лицевой счет.
        /// </summary>
        internal static string AddIdent {
            get {
                return ResourceManager.GetString("AddIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество отвеченных.
        /// </summary>
        internal static string AnsweredAmount {
            get {
                return ResourceManager.GetString("AnsweredAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки.
        /// </summary>
        internal static string App_NavBar {
            get {
                return ResourceManager.GetString("App_NavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать файл.
        /// </summary>
        internal static string AttachmentChooseFile {
            get {
                return ResourceManager.GetString("AttachmentChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать фото из галереи.
        /// </summary>
        internal static string AttachmentChoosePhoto {
            get {
                return ResourceManager.GetString("AttachmentChoosePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать снимок.
        /// </summary>
        internal static string AttachmentTakePhoto {
            get {
                return ResourceManager.GetString("AttachmentTakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить вложение.
        /// </summary>
        internal static string AttachmentTitle {
            get {
                return ResourceManager.GetString("AttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квитанции.
        /// </summary>
        internal static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на .
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить показания.
        /// </summary>
        internal static string ChangePenance {
            get {
                return ResourceManager.GetString("ChangePenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите сообщение....
        /// </summary>
        internal static string ChatPlaceholder {
            get {
                return ResourceManager.GetString("ChatPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Межповерочный интервал:.
        /// </summary>
        internal static string CheckInterval {
            get {
                return ResourceManager.GetString("CheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string CloseApp {
            get {
                return ResourceManager.GetString("CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход для сотрудника.
        /// </summary>
        internal static string ConstLogin {
            get {
                return ResourceManager.GetString("ConstLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  руб. .
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход для жителя.
        /// </summary>
        internal static string DefaultLogin {
            get {
                return ResourceManager.GetString("DefaultLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сохранять пароль.
        /// </summary>
        internal static string DSP {
            get {
                return ResourceManager.GetString("DSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввести код.
        /// </summary>
        internal static string EnterCodeApp {
            get {
                return ResourceManager.GetString("EnterCodeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to События.
        /// </summary>
        internal static string Events_NavBar {
            get {
                return ResourceManager.GetString("Events_NavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заводской №.
        /// </summary>
        internal static string FacNum {
            get {
                return ResourceManager.GetString("FacNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО.
        /// </summary>
        internal static string FIO {
            get {
                return ResourceManager.GetString("FIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        internal static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрытое.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицевой счет: .
        /// </summary>
        internal static string Ident {
            get {
                return ResourceManager.GetString("Ident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфо.
        /// </summary>
        internal static string InfoApp {
            get {
                return ResourceManager.GetString("InfoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последняя проверка:.
        /// </summary>
        internal static string LastCheck {
            get {
                return ResourceManager.GetString("LastCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатели.
        /// </summary>
        internal static string Meters_NavBar {
            get {
                return ResourceManager.GetString("Meters_NavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые показания.
        /// </summary>
        internal static string NewPenance {
            get {
                return ResourceManager.GetString("NewPenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № .
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальные предложения.
        /// </summary>
        internal static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие собрания собственников.
        /// </summary>
        internal static string OSS {
            get {
                return ResourceManager.GetString("OSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передать показания.
        /// </summary>
        internal static string PassPenance {
            get {
                return ResourceManager.GetString("PassPenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить.
        /// </summary>
        internal static string PayApp {
            get {
                return ResourceManager.GetString("PayApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История платежей.
        /// </summary>
        internal static string PayHistory {
            get {
                return ResourceManager.GetString("PayHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж обрабатывается .
        /// </summary>
        internal static string PayProcess {
            get {
                return ResourceManager.GetString("PayProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        internal static string Pays {
            get {
                return ResourceManager.GetString("Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        internal static string Pays_NavBar {
            get {
                return ResourceManager.GetString("Pays_NavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показания переданы.
        /// </summary>
        internal static string PenencePassed {
            get {
                return ResourceManager.GetString("PenencePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход по номеру телефона.
        /// </summary>
        internal static string PhoneLogin {
            get {
                return ResourceManager.GetString("PhoneLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string Prof {
            get {
                return ResourceManager.GetString("Prof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string Profile_NavBar {
            get {
                return ResourceManager.GetString("Profile_NavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество вопросов.
        /// </summary>
        internal static string QuestionsAmount {
            get {
                return ResourceManager.GetString("QuestionsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опросы.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать ответы.
        /// </summary>
        internal static string QuizResult {
            get {
                return ResourceManager.GetString("QuizResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазин.
        /// </summary>
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать пройденные опросы.
        /// </summary>
        internal static string ShowAnsweredQuizes {
            get {
                return ResourceManager.GetString("ShowAnsweredQuizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать закрытые.
        /// </summary>
        internal static string ShowClosedApps {
            get {
                return ResourceManager.GetString("ShowClosedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма к оплате.
        /// </summary>
        internal static string SumToPay {
            get {
                return ResourceManager.GetString("SumToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать в тех.поддержку.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная форма предназначена для обращения в поддержку приложения. Если вы хотите обратиться в .
        /// </summary>
        internal static string TechAdditionalText1 {
            get {
                return ResourceManager.GetString("TechAdditionalText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - создайте заявку тут.
        /// </summary>
        internal static string TechAdditionalText2 {
            get {
                return ResourceManager.GetString("TechAdditionalText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратиться в .
        /// </summary>
        internal static string TechAdditionalText3 {
            get {
                return ResourceManager.GetString("TechAdditionalText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опишите проблему....
        /// </summary>
        internal static string TechPlaceholder {
            get {
                return ResourceManager.GetString("TechPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задайте вопрос здесь, опишите проблему. Мы обязательно вам поможем.
        /// </summary>
        internal static string TechSubtitle {
            get {
                return ResourceManager.GetString("TechSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обращение в тех.поддержку.
        /// </summary>
        internal static string TechTitle {
            get {
                return ResourceManager.GetString("TechTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникли проблемы? .
        /// </summary>
        internal static string Troub {
            get {
                return ResourceManager.GetString("Troub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  рабочих дня.
        /// </summary>
        internal static string WorkDays {
            get {
                return ResourceManager.GetString("WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите нам .
        /// </summary>
        internal static string WriteUs {
            get {
                return ResourceManager.GetString("WriteUs", resourceCulture);
            }
        }
    }
}
